# Website settings
baseurl: "/"
url: "https://dockerupandrunning.com"
thumbnail_path: "docker-up-and-running-cover-3e-early-release-medium.jpg"

# About settings
name: "Docker: Up & Running"
description: "This book is the fastest way to get up and running with Docker and Linux containers. It covers the whole DevOps workflow from initial image creation through production delivery."
website_repo_url: "https://github.com/bluewhalebook/website-docker-up-and-running"
early_release_url: "https://learning.oreilly.com/library/view/docker-up/9781098131814/"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/spkane"
    label: "spkane"
    icon: "twitter-square"
    username: "@spkane"
  twitter2:
    url: "https://twitter.com/relistan"
    label: "kmatthias"
    icon: "twitter-square"
    username: "@relistan"
  linkedin:
    url: "https://www.linkedin.com/in/spkane"
    label: "spkane"
    icon: "linkedin-square"
  linkedin2:
    url: "https://www.linkedin.com/in/karlmatthias/"
    label: "kmatthias"
    icon: "linkedin-square"
  github:
    url: "https://github.com/spkane/"
    label: "spkane"
    icon: "github-square"
  github2:
    url: "https://github.com/relistan/"
    label: "kmatthias"
    icon: "github-square"
  website:
    url: "https://techlabs.sh/"
    label: "spkane"
    icon: "up-right-from-square"
  website2:
    url: "https://relistan.com/"
    label: "kmatthias"
    icon: "up-right-from-square"

# Jekyll build settings
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
